name: Generate time per editor

on:
  # schedule:
    # runs at 4:40 AM BRT (São Paulo Time)
    # - cron: "40 7 * * *"
  workflow_dispatch:
jobs:
  update-readme:
    name: Updated editor-time metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run GitHub Stats Action
        uses: thanhhaudev/github-stats@master
        env:
          BRANCH_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }} # GitHub token, required
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_METRICS: "WAKATIME_SPENT_TIME" # show metrics, separated by comma
          WAKATIME_DATA: "EDITORS" # show data, separated by comma
          SECTION_NAME: editor-time
          WAKATIME_RANGE: all_time
          TIME_ZONE: America/Sao_Paulo
          ONLY_MAIN_BRANCH: "true" # only fetch data from the main branch
          EXCLUDE_FORK_REPOS: "true"
          SHOW_LAST_UPDATE: "false" # show last update time
          PROGRESS_BAR_VERSION: 1
          COMMIT_MESSAGE: Updated editor-time metrics
          # COMMIT_USER_NAME: LucasKazuhiro
          # COMMIT_USER_EMAIL: lucaslko429@gmail.com
